apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: node-tasks
spec:
  workspaces:
    - name: source
  steps:
    - name: npm-install
      image: node:16
      workingDir: $(workspaces.source.path)
      script: |
        npm install
    - name: jasmine-tests
      image: node:16
      workingDir: $(workspaces.source.path)
      script: |
        npx jasmine
