apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-install-task
spec:
  workspaces:
    - name: source
  steps:
    - name: npm-install
      image: node:16
      workingDir: $(workspaces.source.path)
      script: |
        npm install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine-test-task
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: node:16
      workingDir: $(workspaces.source.path)
      script: |
        npx jasmine
